permissions:
  RELOAD_PERM: "aevycore.reload"

messages:
  PREFIX: "&b AevyCore &7Â» "
  NO_PERMS: "&cYou can't execute this command!"
  NO_PLAYER: "&cYou can't execute this command as a player!"
  NO_CONSOLE: "&cYou can't execute this command as the console!"

commands:
  RELOAD_MESSAGE: "&aConfiguration has been reloaded!"
  VERSION_MESSAGE: "&f{version} - {site}"

database:
  ENABLED: false
  DRIVER: "org.mariadb.jdbc.Driver"
  URL: "mariadb"
  IP: "localhost"
  PORT: "3306"
  USER: "root"
  PASSWORD: "root"
  DATABASE: "aevy-core"
  MAX_POOL_SIZE: 6
  DEBUG: true
  PROPERTIES: []
  USE_DEFAULTS: true